import keyMirror from 'keymirror'

export const ACTIONS = keyMirror({
  APPLICATION_ROUTING_ERROR_RESPONSE: null,

  APPLICATION_INIT_REQUEST: null,
  APPLICATION_INIT_SUCCESS: null,
  APPLICATION_INIT_FAIL: null,

  APPLICATION_LOGOUT_REQUEST: null,
  APPLICATION_LOGOUT_SUCCESS: null,
  APPLICATION_LOGOUT_FAIL: null,

  APPLICATION_TOGGLE_GLOBAL_LOADER: null,

  APPLICATION_GET_UNREAD_IMPORTANT_MESSAGES_REQUEST: null,
  APPLICATION_GET_UNREAD_IMPORTANT_MESSAGES_SUCCESS: null,
  APPLICATION_GET_UNREAD_IMPORTANT_MESSAGES_FAIL: null,

  APPLICATION_CHANGE_ORGANIZATIONS: null,

  APPLICATION_SAVE_SETTINGS_REQUEST: null,
  APPLICATION_SAVE_SETTINGS_FAIL: null,
  APPLICATION_SAVE_SETTINGS_SUCCESS: null
})
